### ISSUE TITLE
Add jsonSchema property to parser's type

### ISSUE THREAD

**Issue by adriano2teixeira** [lucasavila00/beff#227]
The parser returns a valid and function jsonSchema version from the typescript type, however it was not added to the parser's type , therefore the developer might struggle to find ways to get the jsonSchema from the parser and might also have problems with typescript errors when developing.

**Comment by lucasavila00** [comment]
The schema now exports in a different file, to allow smaller file sizes https://github.com/lucasavila00/beff/pull/226

**Comment by lucasavila00** [comment]
Notice it did have the types, which were removed by [this merge request](https://github.com/lucasavila00/beff/pull/226)
