### ISSUE TITLE
Error while getting to get zod version of a type when using ad hoc aproach.

### ISSUE THREAD

**Issue by adriano2teixeira** [lucasavila00/beff#228]
For example :
`console.log(b.Object({ hello: b.String()}).zod())`
returns 

      return z.custom((data) => safeParse(data).success, (val) => {
        ^ 
    ReferenceError: z is not defined

**Comment by lucasavila00** [comment]
Fixed by https://github.com/lucasavila00/beff/pull/229, thanks for reporting
